/**
 * 
 */
package tests;

import org.topicquests.support.api.IResult;

/**
 * @author jackpark
 *
 */
public class ResourcePivotTest extends TestRoot {
	private final String DID = "epJOfBzkEem9G9c4W2oLXw";
	/**
	 * 
	 */
	public ResourcePivotTest() {
		IResult r = pivotSuite.listPivotsByResource(DID, 0, 20);
	    System.out.println("A "+r.getResultObject());
		environment.shutDown();
		System.exit(0);
	}

}
/*
{
	"groups": [{
		"groupId": "6xkx19i3",
		"name": "biomed"
	}],
	"title": "An insulin index of foods: the insulin demand generated by 1000-kJ portions of common foods. - PubMed - NCBI",
	"users": ["Gardener@hypothes.is"],
	"url": "https:\/\/www.ncbi.nlm.nih.gov\/pubmed\/9356547",
	"tags": [{
		"label": "Insulin Response",
		"id": "insulin_response"
	}, {
		"label": "Postprandial Insulin Response",
		"id": "postprandial_insulin_response"
	}, {
		"label": "Protein-rich Foods",
		"id": "protein-rich_foods"
	}]
}
*/